questions = [
    "What is the uncertainty principle?",
    "What is the concept of entropy?",
    "What is the concept of hybridization in chemistry?",
    "Why is the sky blue?",
    "What is the role of oxidation states in redox reactions?",
    "How do we determine the structure of molecules using spectroscopy?",
    "What are the main types of galaxies?",
    "How do genes control the traits of an organism?",
    "What are the properties of noble gases?",
    "What are the mechanisms of evolution?",
    "What is the role of the immune system?",
    "How do neurons transmit signals?",
    "What is the role of symmetry in physics?",
    "What are pulsars?",
    "How do genetic mutations occur?",
    "What is the Casimir effect?",
    "What is gravitational lensing?",
    "What is the role of proteins in the body?",
    "What is the Standard Model of particle physics?",
    "What are the effects of habitat loss on ecological networks?",
    "What is the impact of human activities on the environment?",
    "How do tsunamis form and what are their effects?",
    "What are the effects of habitat destruction on species extinction?",
    "what is newton second law?",
    "How do we study and mitigate soil erosion?",
    "What is the role of RNA in gene expression?",
    "How do photosynthetic organisms capture light energy?",
    "What is the role of the atmosphere in regulating climate?",
    "What are the processes of sedimentation?",
    "What are the different types of plate boundaries?",
    "What is the role of environmental law in conservation?",
    "When it comes to waveform graphs, what does `non-convergent` mean?",
    "How are complex ions formed?",
    "How do we conserve natural habitats?",
    "How are chemical reactions balanced?",
    "How does a quantum computer work?",
    "How do we measure and predict earthquakes?",
    "How do parasites affect their hosts?",
    "How do we study and protect marine ecosystems?",
    "What is the difference between a chemical compound and a mixture?",
    "How do plants absorb nutrients?",
    "How do chemical reactions occur at the molecular level?",
    "How do we measure the distance to stars?",
    "What is the role of genetic recombination?",
    "What are fermions and bosons?",
    "What is the function of the nervous system?",
    "How does a particle accelerator work?",
    "How does the circulatory system function?",
    "What is artificial intelligence?",
    "What does a negatively charged object end up?",
    "What are asteroids and comets?",
    "How do chemical reactions affect the environment?",
    "How do astronomers detect black holes?",
    "How does the Earth's atmosphere affect astronomical observations?",
    "What is the concept of spacetime?",
    "How does thermodynamics govern energy transfer?",
    "What are neutron stars?",
    "How do enzymes catalyze biochemical reactions?",
    "What is the role of carbon in organic chemistry?",
    "What is the importance of biodiversity in ecosystems?",
    "How do plants and animals respond to stimuli?",
    "What is the difference between an exothermic and an endothermic reaction?",
    "What is the role of aerosols in the Earth's atmosphere?",
    "How do intermolecular forces affect the properties of substances?",
    "What are the effects of global warming on polar regions?",
    "What is the water cycle?",
    "How do we study and manage coastal ecosystems?",
    "How do we study and mitigate the effects of industrial pollution?",
    "What are the effects of agricultural runoff on water quality?",
    "How do earthquakes occur?",
    "Why is ice less dense than water?",
    "What is the role of ecosystem services in human well-being?",
    "How do we study and manage climate change mitigation?",
    "What are the causes and consequences of deforestation?",
    "What are the effects of environmental pollution on living organisms?",
    "what causes excessive sweating in some and hardly any drop of sweat in others?",
    "How do we study and manage sustainable development?",
    "What is the role of gauge theories in particle physics?",
    "How does the Internet work?",
    "How do plants adapt to their environment?",
    "What are the different types of star clusters?",
    "How do binary star systems work?",
    "What causes the phases of the moon?",
    "What are the stages of the cell cycle?",
    "What is the photoelectric effect?",
    "What is the heliosphere?",
    "How do cells obtain and use energy?",
    "How do animals reproduce?",
    "How do lasers work?",
    "are waves controllable?",
    "How do airplanes stay in the air?",
    "How are galaxies formed?",
    "What is the greenhouse effect?",
    "What is the role of environmental advocacy in policy change?",
    "What is the rock cycle?",
    "What is the role of carbon in the Earth's climate system?",
    "How does the human body maintain homeostasis?",
    "How do black holes form?",
    "How can tartigrades survive in outer space and vacuum?",
    "What are the effects of plastic pollution on marine life?",
    "What is the Schrödinger equation?",
    "Why do standard academic books have to be so expensive? Why are they copyright protected?",
    "How are reaction rates determined?",
    "Why do puddles dry up but not large lakes?",
    "What are the effects of microplastics on the environment?",
    "What are the different types of rocks?",
    "What is the role of environmental policies in protecting ecosystems?",
    "What is the role of the endocrine system?",
    "How do acids and bases react with each other?",
    "How does the digestive system process food?",
    "What is the role of the ozone layer?",
    "What are the major types of soil?",
    "How does Bluetooth work?",
    "What is the Higgs boson?",
    "How does soap clean?",
    "How do transition metals differ from other elements?",
    "What is a virus?",
    "What is the difference between a homogeneous and a heterogeneous catalyst?",
    "What are the differences between prokaryotic and eukaryotic cells?",
    "What is string theory?",
    "What is the difference between a nova and a supernova?",
    "What is the Goldilocks zone?",
    "What is the difference between a planet and a dwarf planet?",
    "How do we measure concentration in chemistry?",
    "How does nuclear fusion work?",
    "What is quantum entanglement?",
    "What is the role of ligands in coordination chemistry?",
    "How does gravity affect time?",
    "What is the difference between classical and quantum physics?",
    "What is the concept of stereochemistry?",
    "What is DNA and why is it important?",
    "Why are planets round?",
    "What is the concept of quantum entanglement?",
    "What is the role of environmental technology in pollution control?",
    "What is the function of the excretory system?",
    "How do we manage waste sustainably?",
    "Why are trans fats bad for you, what do they do to your body?",
    "What are the effects of chemical pollutants on human health?",
    "What is the role of the hydrosphere in the Earth's climate system?",
    "What are the principles of ecological succession?",
    "How do pollutants affect air quality?",
    "How do ecosystems function and what are their components?",
    "What are the effects of climate change on biodiversity?",
    "How do we study and manage sustainable transportation?",
    "What are the different types of cells in the human body?",
    "What is the role of biodiversity in ecosystem stability?",
    "What are the effects of ocean acidification on marine ecosystems?",
    "What is the role of solvents in chemical reactions?",
    "What is the role of chloroplasts in plant cells?",
    "Why is a password with both numbers and letters stronger than one with only letters? Attackers will include numbers in their brute force attempts anyway, so how does it make a difference?",
    "Why isn’t Switzerland a desert?",
    "If air molecules are acting like masses on a spring in sound waves, how are different frequencies possible?",
    "How do so many cave dwelling species evolve similar exotic traits like losing eyes, clear skin, etc?",
    "How come if we jump inside a train we land on the same spot but if jumped on top of it we land at a different one?",
    "Is there a minimum gravity required to hold a breathable atmosphere?",
    "What, if any, are mechanisms human body uses to prevent/resolve unwanted blood clots?",
    "Why don’t plants get cancer?",
    "Is there another reservoir for the herpes simplex viruses than humans?",
    "What Factors lead to Polygyny in Animals, and what Factors lead to Monogamy?",
    "Why can the speed of light in a medium be faster than c?",
    "Why are photons the only force carriers that are “visible”?",
    "How do we identify gene variants?",
    "What was in our area of space before our sun existed?",
    "What's with the apocalyptic floods we're seeing more and more?",
    "Is Betelgeuse (almost) spherical like other stars or is it more like a blob?",
    "If birds evolved from dinosaurs, what natural selection feature of the birds made them evolve to a much smaller size compared to dinos?",
    "How do amps pick up radio signals?",
    "During pregnancy what provides the pressure to maintain the amniotic sac and force the belly to stretch and grow?",
    "How do photons represent electromagnetic fields over large distances with many particles?",
    "Is grey fox really a fox?",
    "When the 1st logarithmic scales for slide rules were created, how did they make *precise* lengths and divisions? Also - is there a geometric construction that precisely gives logarithmic scales?",
    "Does total fertility rate calculation account for time?",
    "If birds are descendents of reptiles, when and how did they become warm blooded?",
    "If the laws of physics would work the same if time flowed backwards, how does entropy play into that?",
    "When editing DNA/genes, how does the human body know to replicate the edited version vs. the original?",
    "Voyager Spacecraft just lucky?",
    "Can animals recognise depictions of themselves through art?",
    "Do we know what the cores of stars look like?",
    "Was any of the ancestors of the penguin able to fly?",
    "How does the anatomy of the eyes prevent water from entering the ocular cavity? Is there some biological watertight seal? Why doesn’t water get in when say diving or when rinsing one’s eyes in the faucet?",
    "How can your immune system allergically react to a substance that hasn't entered your body/bloodstream?",
    "Is it true CO2 emission sequestering is useless and we should only care about reduction or avoidance?",
    "Why did it take so long for Apollo 11 to reach the moon?",
    "Do fish have saliva?",
    "Are the images from the James Webb telescope the true images captured or is there some rendering or interpretation added in?",
    "How does testosterone levels during puberty affect the growth and development of the penis?",
    "In 250 million years, how much longer will a year be?",
    "Will the moon ever be destroyed?",
    "Windmills, why aren’t they always “on”?",
    "Is it possible to have an ice age  and a supercontinent at the same time?",
    "Why does Delta IV set itself on fire when other rockets don't?",
    "If we say time is the 4th dimension, why don't we just attribute dimensions to other things, like `the 5th dimension is charge`?",
    "Do any marine mammals have underwater sense of smell?",
    "Why does spinning your body in a circle result in dizziness, nausea, and vomiting?",
    "How does the lung expel germs?",
    "Does the Amazon rainforest have an effect on the Sahara desert?",
    "How do we know what is normal for climate fluctuations throughout Earth's history if we only have limited data points rather than day to day statistics of pre-human weather?",
    "The moon has many craters visible to the naked eye, what would the impact event that created the largest of them have looked like to the naked eye from earth?",
    "Now that one of the three major strains of Influenza is effectively extinct, have the other two increased in prevalence to compensate?",
    "Can dinosaur bones that are created in sandstone have a thin layer of sandstone covering the bones that make them not look like bones?",
    "What’s happening in your body that causes the sensation of fatigue? Not the macro causes like poor sleep, etc. Decrease or increase of a particular hormone or something along those lines?",
    "Why did the Laurentide Ice Sheet form and receed like it did?",
    "How are the varying kinetic energies and momentums from different reference frames balanced when dealing with relativistic speeds?",
    "How many stars in the sky don't exist?",
    "What does an unborn baby have in it's lungs?",
    "Why are there dunes?",
    "In placental mammals, does the placenta come from the embryo or the mother?",
    "Why is there a visible cone of a tornado when it’s made of rotating air?",
    "do we have more or less trees than we did 30 years ago?",
    "Does being exposed to a disease during a period of immunity prolong your resistance?",
    "Why five fingers? Why not 3, 7, or 9?",
    "What causes arctic animals to shift between summer and winter coats?",
    "Are there invasive species from the Americas in Africa/Asia/Europe?",
    "Mt Rainier lasted erupted in 1450 CE and has a pointy peak. How long does it take for a volcano to turn into a peak?",
    "How long would it take for the land under antarctica to fully resurface if all the ice above it dissappeared this instant?",
    "How long does an `evolution` of a rhinovirus last before going extinct?",
    "Is energy actually conserved?",
    "How can gene edits prevent viral infection?",
    "It is widely said that age of the universe is around 14 billion years. According to whom?",
    "Why did NASA's Orion capsule change colour after reentry?",
    "Why were there massive spikes in exoplanets discovered in 2014 and 2016?",
    "How does both nuclear fusion and nuclear fission release energy?",
    "Axiomatic definition of classes of L functions?",
    "How exactly does the Pauli Exclusion Principle play a role in contact forces vs electrostatic repulsion?",
    "Why is one side of the Mississippi River flat, and the other side hilly?",
    "What dictates which field is excited in QFT?",
    "If moving at near (90+%) light speed, can a person travel 'n' light-years and experience LESS than 'n' years, or is their minimum perceived travel time equal to the number of light years in the journey?",
    "What were all the small explosion tests in Oppenheimer?",
    "How is the Internet speed at the ISS over 1GB/sec?",
    "Which river on earth is currently changing its course the fastest/slowest? How can we tell?",
    "How do birds know which way is south?",
    "How do researchers quantify depression,anxiety,bipolar etc in mice models?",
    "Can crows from different regions communicate?",
    "How can eyes heal themselves when they have immune privilege?",
    "How fast do macrophages move around?",
    "Why do some insect fossils still have colors ?",
    "How does lactose enter lac operon?",
    "What is the deal with co-occurring allergies that don't make sense in terms of clades?",
    "What's the layman definitions for the SI units?",
    "Why can't cats with FIV (Feline Immunodeficiency Virus) be given medication for HIV (Human Immunodeficiency Virus)?",
    "How do researchers give lab rats cancer?",
    "Why do banana peels connected to the banana turn black in the fridge even if not ripe?",
    "What's the limit to the placebo effect?",
    "Do octopodes change color beyond the visible spectrum of light?",
    "Is the flavor of a strawberry concentrated in certain parts of the fruit, or is it distributed evenly throughout?",
    "Why is body/facial hair such a strongly sex-linked trait in humans? Is there any potential evolutionary reason for it being correlated with testosterone and present largely only in males?",
    "if you put a scale underwater with the face pointing up, would it show the weight of the water above it?",
    "How is it possible to hear sound under water?",
    "How do ecosystems function?",
    "What are the fundamental forces of nature?",
    "How do electric and magnetic fields interact?",
    "What is the process of mitosis and meiosis?",
    "What is the significance of the Hubble Space Telescope?",
    "What is evolution?",
    "Why do leaves fall in autumn?",
    "Why do we have seasons?",
    "How do planetary rings form?",
    "How do cameras work?",
    "Why does salt melt ice?",
    "What are allotropes and how do they differ?",
    "How do hormones regulate bodily functions?",
    "What is a supernova?",
    "What causes thunder?",
    "What is the role of ribosomes in protein synthesis?",
    "What causes earthquakes?",
    "How TVs switched from b&w to color?",
    "What are the different types of sedimentary rocks?",
    "What is the periodic table and how is it organized?",
    "What is the role of environmental monitoring in protecting ecosystems?",
    "What are the processes of tectonic deformation?",
    "What are the effects of urbanization on natural habitats?",
    "How does light behave as both a wave and a particle?",
    "How do we study and manage air quality?",
    "What are the effects of land use change on ecosystems?",
    "What is the role of conservation biology in protecting species?",
    "How do we study and protect wetlands?",
    "why are heartbeat, pulse, breathing like a wave? Why do wave exists in the universe?",
    "What is the role of neurotransmitters in the brain?",
    "What are the layers of the Earth?",
    "How do plants reproduce sexually and asexually?",
    "What is the role of geochemical cycles in the Earth's system?",
    "How are mountains formed?",
]